/* 
VARIABLE SCOPE = IS WHERRE A VARIABLE IS ACCESSIBLE

LET = VARIABLES ARE LIMITED TO BLOCK SCOPE AND CANNOT BE USED OUTSIDE THE {} 
VAR = VARIABLES ARE LIMITED TO A FUNCTION () {}

GLOBAL VARIABLE = IS DECLARED OUTSIDE OF ANY FUNCTION (let name = "Fola") DON'T USE (var name = "Fola")

(IF GLOBAL, VAR WILL CHANGES BROWSER'S WINDOW PROPERTIES)
*/
