/*  
DOM = DOCUMENT OBJECT MODULE (TECHNICALLY IT IS AN    API = APLICATION PROGRAMMING INTERFACE)
        IT IS AN IMTERFACE FOR CHANGING THE CONTENT OF A PAGE

  IT IS ARRANGED IN A HIERARCHICAL TREE.
  IT IS THE REPRESENTATION OF AN HTML DOCUMENT.

  BY INTERACTING WITH DOM, WE CAN CHANGE THE ELEMENTS OF OUR WEBPAGE
*/

console.log(document); // THIS WILL DISPLAY THE DOM AND EVERYTHING IN IT

console.dir(document); // THIS WILL LIST ALL THE PROPERTIES OF THE DOM

console.log(document.title); // THIS WILL DISPLAY THE TITLE OF THE DOCUMENT

console.log(document.URL); // THIS WILL DISPLAY THE URL OF THE WEBPAGE

// TO CHANGE THE PROPERTIES OF ANY OF THESE THINGS

document.title = "Title goes here!"; // CHANGES THE DOCUMENT TITLE

document.location /* = "http://www.google.com" */; // CHANGES THE LOCATION

document.body.style.backgroundColor = "skyblue"; // TO CHANGE THE BACKGROUND COLOR

document.getElementById("myDiv").innerHTML = "Hello";
